---
- hosts: web
  become: true
  gather_facts: True
  tasks:
    - name: Adding Docker APT key
      apt_key:
        keyserver: hkp://p80.pool.sks-keyservers.net:80
        id: 58118E89F3A912897C070ADBF76221572C52609D

    - name: Adding Docker APT repository
      apt_repository:
        repo: deb https://apt.dockerproject.org/repo ubuntu-trusty main
        update_cache: yes

    - name: Uninstalling the old version of docker if exists
      apt:
        name: lxc-docker
        purge: yes
      failed_when: no

    - name: Install latest version of Docker
      apt:
        name: docker-engine

    - name: Adding ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Adding teamcity user to docker group
      user:
        name: teamcity
        groups: docker
        append: yes

    - name: Installing docker compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.5.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 0755

    - name: install pip
      apt: name=python-pip state=latest

    - name: work around docker-py
      pip:
       executable=/usr/bin/pip
       name=docker-py
       state=present
       version=1.8.1

    - name: application container
      docker:
        name: myapplication
        image: wordpress
        state: reloaded
        pull: always

    - name: "Launch database container"
      docker:
        name: db
        image: mariadb
        env:
          MYSQL_ROOT_PASSWORD: P@$$w0rd

    - name: "Launch wordpress container"
      docker:
        name: wordpress
        image: wordpress
        links:
        - db:mysql
        ports:
          - 8080:80
